import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import RootHeader from "./ui/layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-14 py-6`}>
        <RootHeader></RootHeader>
        {children}
      </body>
    </html>
  );
}
